### ISSUE TITLE
`statistics(count)' does not work

### ISSUE THREAD

**Issue by lotandre** [matthieugomez/stata-sumup#11]
Contrary to the help file syntax, using `statistics(count)` returns an error
`count does not correspond to any stat
invalid syntax
`

Using `n`  or `N`  instead of `count`  works as intended, nonetheless.

**Comment by matthieugomez** [comment]
Thanks for the report. Fixed with https://github.com/matthieugomez/sumup.ado/commit/d627cb5163ab89237577473320e71345e5340bdb
