### ISSUE TITLE
Installation link is not working

### ISSUE THREAD

**Issue by jjchern** [matthieugomez/stata-sumup#6]
I run the command in Stata console but get the following error message.

``` stata
. net install sumup, from(https://github.com/matthieugomez/stata-sumup/raw/master/)
unknown network protocol
https://github.com/matthieugomez/stata-sumup/raw/master/ either
  1)  is not a valid URL, or
  2)  could not be contacted, or
  3)  is not a Stata download site (has no stata.toc file).
r(671);
```

Thanks for the program!

**Comment by matthieugomez** [comment]
You need stata 13 to read https link. I've uploaded the README with installation instructions if you have a version < 13. Please tell me if it's working!

**Comment by jjchern** [comment]
I just tried it and it works. It appears that there's no help document. But that's not a big deal, I can always go back to your readme file for examples. Thanks again!

**Comment by jjchern** [comment]
I think another approach to ease the installation process for lower Stata version is to set up a github page  for the repo and copy the `*.ado`, `*.pkg`, and `stata.toc` files to the `gh-page` branch. Then one can install the program with

```
net install sumup, from(http://matthieugomez.github.io/stata-sumup)
```

I wonder if there's an `install_github` or `Pkg_add` Stata program that makes installing ado file from Github easier.

**Comment by matthieugomez** [comment]
Unfortunately, github does not provide `http` links so I dont think it's possible
